/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagesSettingsRouteImport } from './routes/pages.settings'
import { Route as PagesPublishRouteImport } from './routes/pages.publish'
import { Route as PagesIconSystemRouteImport } from './routes/pages.icon-system'
import { Route as PagesEditProfileRouteImport } from './routes/pages.edit-profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSettingsRoute = PagesSettingsRouteImport.update({
  id: '/pages/settings',
  path: '/pages/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesPublishRoute = PagesPublishRouteImport.update({
  id: '/pages/publish',
  path: '/pages/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesIconSystemRoute = PagesIconSystemRouteImport.update({
  id: '/pages/icon-system',
  path: '/pages/icon-system',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesEditProfileRoute = PagesEditProfileRouteImport.update({
  id: '/pages/edit-profile',
  path: '/pages/edit-profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pages/edit-profile': typeof PagesEditProfileRoute
  '/pages/icon-system': typeof PagesIconSystemRoute
  '/pages/publish': typeof PagesPublishRoute
  '/pages/settings': typeof PagesSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pages/edit-profile': typeof PagesEditProfileRoute
  '/pages/icon-system': typeof PagesIconSystemRoute
  '/pages/publish': typeof PagesPublishRoute
  '/pages/settings': typeof PagesSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pages/edit-profile': typeof PagesEditProfileRoute
  '/pages/icon-system': typeof PagesIconSystemRoute
  '/pages/publish': typeof PagesPublishRoute
  '/pages/settings': typeof PagesSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pages/edit-profile'
    | '/pages/icon-system'
    | '/pages/publish'
    | '/pages/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pages/edit-profile'
    | '/pages/icon-system'
    | '/pages/publish'
    | '/pages/settings'
  id:
    | '__root__'
    | '/'
    | '/pages/edit-profile'
    | '/pages/icon-system'
    | '/pages/publish'
    | '/pages/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PagesEditProfileRoute: typeof PagesEditProfileRoute
  PagesIconSystemRoute: typeof PagesIconSystemRoute
  PagesPublishRoute: typeof PagesPublishRoute
  PagesSettingsRoute: typeof PagesSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/settings': {
      id: '/pages/settings'
      path: '/pages/settings'
      fullPath: '/pages/settings'
      preLoaderRoute: typeof PagesSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/publish': {
      id: '/pages/publish'
      path: '/pages/publish'
      fullPath: '/pages/publish'
      preLoaderRoute: typeof PagesPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/icon-system': {
      id: '/pages/icon-system'
      path: '/pages/icon-system'
      fullPath: '/pages/icon-system'
      preLoaderRoute: typeof PagesIconSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/edit-profile': {
      id: '/pages/edit-profile'
      path: '/pages/edit-profile'
      fullPath: '/pages/edit-profile'
      preLoaderRoute: typeof PagesEditProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PagesEditProfileRoute: PagesEditProfileRoute,
  PagesIconSystemRoute: PagesIconSystemRoute,
  PagesPublishRoute: PagesPublishRoute,
  PagesSettingsRoute: PagesSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
